// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpAux.IO")>]
[<assembly: AssemblyProductAttribute("FSharpAux")>]
[<assembly: AssemblyDescriptionAttribute("Auxiliary functions and data structures for F# programming language")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpAux.IO"
    let [<Literal>] AssemblyProduct = "FSharpAux"
    let [<Literal>] AssemblyDescription = "Auxiliary functions and data structures for F# programming language"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
