// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpAux")>]
[<assembly: AssemblyProductAttribute("FSharpAux")>]
[<assembly: AssemblyDescriptionAttribute("Auxiliary functions and data structures for F# programming language")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpAux"
    let [<Literal>] AssemblyProduct = "FSharpAux"
    let [<Literal>] AssemblyDescription = "Auxiliary functions and data structures for F# programming language"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
