// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Care.IO")>]
[<assembly: AssemblyProductAttribute("FSharp.Care")>]
[<assembly: AssemblyDescriptionAttribute("Auxiliary functions and data structures for F# programming language")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Care.IO"
    let [<Literal>] AssemblyProduct = "FSharp.Care"
    let [<Literal>] AssemblyDescription = "Auxiliary functions and data structures for F# programming language"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
