name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: make script executable
      run: chmod u+x build.sh
    - name: Build and test
      working-directory: ./
      run: ./build.sh runtests

  build-and-test-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Build and test
      working-directory: ./
      run: ./build.cmd runtests
